# Generated by Django 4.2.5 on 2023-09-11 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("st_auth", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="geolocation",
            name="signed_up_on_holiday",
            field=models.BooleanField(default=None, null=True),
        ),
    ]
