# Generated by Django 4.2.5 on 2023-09-11 12:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("st_auth", "0002_alter_geolocation_signed_up_on_holiday"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="geolocation",
            name="id",
        ),
        migrations.AlterField(
            model_name="geolocation",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                related_name="geolocation",
                serialize=False,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
