#  Template python-build

#  This template allows you to validate your python code.
#  The workflow allows running tests and code linting on the default branch.

image: python:3.11

pipelines:
  default:
    - parallel:
      - step:
          name: Test
          caches:
            - pip
          script:
            - curl -sSL https://install.python-poetry.org | python3 - --version 1.6.1
            - export PATH="$HOME/.local/bin:$PATH"
            - poetry install
            - poetry run pytest tests/unit --cov func --cov-branch --cov-report term-missing
      - step:
          name: Lint code
          script:
            # Enforce style consistency across Python projects https://flake8.pycqa.org
            - pip install flake8
            - flake8 . --extend-exclude=dist,build --show-source --statistics
