image: python:3.11

pipelines:
  default:
    - parallel:
      - step:
          name: Test
          caches:
            - pip
            - docker
          script:
            - curl -sSL https://install.python-poetry.org | python3 - --version 1.6.1
            - export PATH="$HOME/.local/bin:$PATH"
            - export ABSTRACT_API_EMAIL_URL=$ABSTRACT_API_EMAIL_URL
            - export ABSTRACT_API_EMAIL_KEY=$ABSTRACT_API_EMAIL_KEY
            - export CELERY_BROKER_URL=$CELERY_BROKER_URL
            - export CELERY_RESULT_BACKEND=$CELERY_RESULT_BACKEND
            - export DATABASE=$DATABASE
            - export DJANGO_ROOT_URLCONF=$DJANGO_ROOT_URLCONF
            - export DJANGO_SECRET_KEY=$DJANGO_SECRET_KEY
            - export POSTGRES_DB=$POSTGRES_DB
            - export POSTGRES_HOST=$POSTGRES_HOST
            - export POSTGRES_PASSWORD=$POSTGRES_PASSWORD
            - export POSTGRES_PORT=$POSTGRES_PORT
            - export POSTGRES_USER=$POSTGRES_USER
            - export RABBITMQ_DEFAULT_USER=$RABBITMQ_DEFAULT_USER
            - export RABBITMQ_DEFAULT_PASS=$RABBITMQ_DEFAULT_PASS
            - >
              docker run --publish 5432:5432 --name db -e POSTGRES_PASSWORD=$POSTGRES_PASSWORD \
                -e POSTGRES_DB=$POSTGRES_DB -e POSTGRES_HOST=$POSTGRES_HOST -e POSTGRES_PORT=$POSTGRES_PORT \
                -e POSTGRES_USER=$POSTGRES_USER -d postgres
            - poetry install
            - poetry run pytest --ignore tests --cov
          services:
            - docker
      - step:
          name: Lint code
          script:
            # Enforce style consistency across Python projects https://flake8.pycqa.org
            - pip install flake8
            - flake8 . --extend-exclude=dist,build --show-source --statistics
