version: "3.8"

services:
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
    ports:
      - "5432:5432"

  api:
    build: .
    command: >
      sh -c "cd social_text &&
             poetry run python manage.py makemigrations &&
             poetry run python manage.py migrate &&
             poetry run python manage.py collectstatic --no-input &&
             poetry run gunicorn social_text.asgi:application -w 4 -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000"
    volumes:
      - .:/app:z
      - static_files:/app/social_text/static
    expose:
      - 8000
    environment:
      - SECRET_KEY=${DJANGO_SECRET_KEY}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=${POSTGRES_USER}

  nginx:
    build: ./nginx
    ports:
      - "1337:80"
    depends_on:
      - api
    volumes:
      - static_files:/app/social_text/static

volumes:
  static_files:
  postgres_data:
