version: "3.8"

services:
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=db
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
    ports:
      - ${POSTGRES_PORT}:5432

  db-test:
    image: postgres
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_PORT_TEST=${POSTGRES_PORT_TEST}
      - POSTGRES_USER=${POSTGRES_USER}
    ports:
      - ${POSTGRES_PORT_TEST}:5432
    expose:
      - ${POSTGRES_PORT_TEST}
    profiles:
      - test

  api:
    build: .
    command: >
      sh -c "poetry run python manage.py makemigrations &&
             poetry run python manage.py migrate &&
             poetry run python manage.py collectstatic --no-input &&
             poetry run gunicorn social_text.asgi:application -w 4 -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000"
    volumes:
      - .:/app:z
      - static_files:/app/static
    expose:
      - 8000
    environment:
      - ABSTRACT_API_EMAIL_URL=${ABSTRACT_API_EMAIL_URL}
      - ABSTRACT_API_EMAIL_KEY=${ABSTRACT_API_EMAIL_KEY}
      - ABSTRACT_API_GEOLOCATION_URL=${ABSTRACT_API_GEOLOCATION_URL}
      - ABSTRACT_API_GEOLOCATION_KEY=${ABSTRACT_API_GEOLOCATION_KEY}
      - ABSTRACT_API_HOLIDAY_URL=${ABSTRACT_API_HOLIDAY_URL}
      - ABSTRACT_API_HOLIDAY_KEY=${ABSTRACT_API_HOLIDAY_KEY}
      - CELERY_BROKER_URL=amqp://admin:mypass@rabbit:5672
      - CELERY_RESULT_BACKEND=redis://redis:6379
      - DJANGO_CSRF_TRUSTED_ORIGINS=${DJANGO_CSRF_TRUSTED_ORIGINS}
      - DJANGO_ROOT_URLCONF=${DJANGO_ROOT_URLCONF}
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=${POSTGRES_HOST_DOCKER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
    profiles:
      - runserver
      - test

  nginx:
    build: ./nginx
    ports:
      - "1337:80"
    depends_on:
      - api
    volumes:
      - static_files:/app/static
    profiles:
      - runserver
      - test

  rabbit:
    hostname: rabbit
    image: rabbitmq:3.12-management-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
    ports:
      - "5672:5672"
      - "15672:15672"

  redis:
    image: redis:7.2-alpine
    hostname: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      sh -c "celery -A social_text worker -l INFO"
    volumes:
      - .:/app:Z
    links:
      - rabbit
      - redis
    depends_on:
      - rabbit
    environment:
      - ABSTRACT_API_EMAIL_URL=${ABSTRACT_API_EMAIL_URL}
      - ABSTRACT_API_EMAIL_KEY=${ABSTRACT_API_EMAIL_KEY}
      - ABSTRACT_API_GEOLOCATION_URL=${ABSTRACT_API_GEOLOCATION_URL}
      - ABSTRACT_API_GEOLOCATION_KEY=${ABSTRACT_API_GEOLOCATION_KEY}
      - ABSTRACT_API_HOLIDAY_URL=${ABSTRACT_API_HOLIDAY_URL}
      - ABSTRACT_API_HOLIDAY_KEY=${ABSTRACT_API_HOLIDAY_KEY}
      - CELERY_BROKER_URL=amqp://admin:mypass@rabbit:5672
      - CELERY_RESULT_BACKEND=redis://redis:6379
      - DJANGO_CSRF_TRUSTED_ORIGINS=${DJANGO_CSRF_TRUSTED_ORIGINS}
      - DJANGO_ROOT_URLCONF=${DJANGO_ROOT_URLCONF}
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=${POSTGRES_HOST_DOCKER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=${POSTGRES_USER}

volumes:
  static_files:
  postgres_data:
  redis_data:
