openapi: 3.0.3
info:
  title: SocialText API Specification
  version: 1.0.0
  description: SocialText is a text based social media app.
paths:
  /api/v1/auth/signup:
    post:
      operationId: v1_auth_signup_create
      tags:
      - v1
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SignUp'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/SignUp'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/SignUp'
        required: true
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenResponse'
          description: ''
        '400':
          description: '{"error": "user_already_exists"}'
components:
  schemas:
    SignUp:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        email:
          type: string
          format: email
          title: Email address
          maxLength: 254
        password:
          type: string
          writeOnly: true
          maxLength: 128
      required:
      - id
      - password
    TokenResponse:
      type: object
      properties:
        email:
          type: string
        token:
          type: string
      required:
      - email
      - token
  securitySchemes:
    jwtAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
